name: entrymvc
description: EntryMVC built with polymer.dart
version: 0.15.4
dependencies:
  polymer: ^1.0.0-rc.2
  web_components:
  browser:
  polymer_elements:
    git: git://github.com/dart-lang/polymer_elements.git
transformers:
- polymer:
    entry_points:
    - web/index.html
    - test/listorder_test.html
    - test/markdone_test.html
    - test/mainpage_test.html
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
dev_dependencies:
  test: ^0.12.3
environment:
  sdk: ">=1.8.0 <2.0.0"
